import type { EventDef } from "../../../../engine/types.js";

export const ACCIDENT: EventDef[] = [
  {
    id: "hay_cart",
    category: "accident",
    weight: 4,
    fatal: 0.2,
    fatalMitigatedBy: "health",
    textVariants: ["fell off a hay cart and lived to be laughed at."],
    deathText: ["fell from a hay cart and was found beneath it by morning."],
  },
  {
    id: "kicked_by_donkey",
    category: "accident",
    weight: 3,
    fatal: 0.15,
    fatalMitigatedBy: "health",
    textVariants: ["kicked by a donkey. Held a grudge. So did the donkey."],
    deathText: ["was kicked by a donkey in a dispute over a gate."],
  },
  {
    id: "lightning_blasphemy",
    category: "accident",
    weight: 2,
    fatal: 0.5,
    textVariants: ["cursed the weather and the weather, notably, did not respond."],
    deathText: ["was struck by lightning mid-blasphemy. The parish drew conclusions."],
  },
  {
    id: "fell_in_the_well",
    category: "accident",
    weight: 3,
    fatal: 0.3,
    fatalMitigatedBy: "health",
    conditions: [{ notFlag: "item:bucket" }],
    textVariants: ["slipped at the well and was hauled out, damp and humbled."],
    deathText: ["fell down the village well, which the village then had to re-dig."],
  },
  {
    id: "barn_fire",
    category: "accident",
    weight: 3,
    tags: ["fire"],
    fatal: 0.22,
    fatalMitigatedBy: "health",
    textVariants: ["a barn caught light and you beat it out with a wet sack and luck."],
    deathText: ["died in a barn fire, going back for the pig."],
  },
  {
    id: "gored_by_bull",
    category: "accident",
    weight: 2,
    fatal: 0.35,
    fatalMitigatedBy: "health",
    textVariants: ["a bull took exception to you and you took to a fence, quickly."],
    deathText: ["was gored by the parish bull, who was cleared of all charges."],
  },
  {
    id: "drowned_ford",
    category: "accident",
    weight: 2,
    fatal: 0.3,
    fatalMitigatedBy: "health",
    conditions: [{ notFlag: "item:boots" }],
    textVariants: ["misjudged the ford in spate and washed up two fields down, alive."],
    deathText: ["drowned crossing a swollen ford on a shortcut home."],
  },
  {
    id: "froze_in_winter",
    category: "accident",
    weight: 3,
    fatal: 0.2,
    fatalMitigatedBy: "health",
    conditions: [{ notFlag: "item:cloak" }],
    textVariants: ["a hard winter nearly took your toes, but you kept them all."],
    deathText: ["froze in a hard winter, having gambled the firewood."],
  },
  {
    id: "tree_fell",
    category: "accident",
    weight: 2,
    fatal: 0.25,
    fatalMitigatedBy: "health",
    textVariants: ["a tree came down where you'd been standing a moment before."],
    deathText: ["was felled by a tree you were, ironically, felling."],
  },
  {
    id: "bee_swarm",
    category: "accident",
    weight: 3,
    statEffects: { health: -1 },
    textVariants: ["robbed the wrong hive and ran a memorable distance."],
  },
  {
    id: "cut_hand_reaping",
    category: "accident",
    weight: 4,
    statEffects: { health: -1 },
    textVariants: ["cut your hand at the reaping and it healed crooked."],
  },
  {
    id: "ice_gives_way",
    category: "accident",
    weight: 2,
    fatal: 0.28,
    fatalMitigatedBy: "health",
    textVariants: ["the mill-pond ice cracked but held long enough."],
    deathText: ["went through the ice on the mill-pond and did not come up."],
  },
];
