import type { EventDef } from "../../../../engine/types.js";

export const DISEASE: EventDef[] = [
  {
    id: "sweating_sickness",
    category: "disease",
    weight: 8,
    tags: ["plague"],
    fatal: 0.35,
    fatalMitigatedBy: "health",
    textVariants: [
      "survived the sweating sickness. The pig did not.",
      "took the sweats, and sweated through it.",
      "felt the sweats come on at Matins and, against all odds, saw Vespers.",
    ],
    deathText: [
      "died of the sweating sickness, well before dinner.",
      "was merry at breakfast and dead by supper, of the sweats.",
    ],
  },
  {
    id: "the_flux",
    category: "disease",
    weight: 9,
    fatal: 0.3,
    fatalMitigatedBy: "health",
    textVariants: [
      "caught the flux and, unusually, recovered.",
      "endured a week of the flux and lived to complain of it.",
    ],
    deathText: [
      "died of the flux, having ignored the physician's advice to be bled, which was also wrong.",
      "died of the bloody flux, three days into Lent.",
    ],
  },
  {
    id: "the_ague",
    category: "disease",
    weight: 7,
    fatal: 0.16,
    fatalMitigatedBy: "health",
    textVariants: [
      "shivered through a bout of the ague.",
      "shook with the ague for a fortnight and blamed the marsh.",
    ],
    deathText: ["died of the ague, blaming the fenland air, correctly."],
  },
  {
    id: "the_pestilence",
    category: "disease",
    weight: 6,
    tags: ["plague"],
    fatal: 0.5,
    fatalMitigatedBy: "health",
    minAge: 13,
    textVariants: [
      "walked through a plague year untouched. Nobody knows why.",
      "buried half the parish in a plague year and did not so much as cough.",
    ],
    deathText: [
      "died of the pestilence, alongside most of the parish.",
      "died of the great mortality, and the bell did not stop tolling for a week.",
    ],
  },
  {
    id: "the_pox",
    category: "disease",
    weight: 5,
    fatal: 0.22,
    fatalMitigatedBy: "health",
    textVariants: [
      "took the pox and kept the scars as souvenirs.",
      "recovered from the pox, pitted but proud.",
    ],
    deathText: ["died of the pox, unlovely to the last."],
  },
  {
    id: "winter_fever",
    category: "disease",
    weight: 6,
    fatal: 0.14,
    fatalMitigatedBy: "health",
    conditions: [{ notFlag: "item:cloak" }],
    textVariants: ["a winter fever laid you low, but the fire held it off."],
    deathText: ["died of a winter fever, having wagered the firewood on ale."],
  },
  {
    id: "the_bleeding_physician",
    category: "disease",
    weight: 4,
    conditions: [{ notFlag: "beenBled" }],
    setsFlags: ["beenBled"],
    statEffects: { health: -1, wealth: -1 },
    textVariants: [
      "the physician bled you for your health. You felt worse and poorer.",
      "a learned physician applied leeches, a horoscope, and a large bill.",
    ],
  },
  {
    id: "toothache",
    category: "disease",
    weight: 5,
    statEffects: { health: -1 },
    textVariants: [
      "a rotten tooth was pulled by the blacksmith, who charged less than the barber.",
      "suffered the toothache and prayed to St Apollonia, patron of teeth.",
    ],
  },
  {
    id: "the_dropsy",
    category: "disease",
    weight: 4,
    minAge: 35,
    fatal: 0.18,
    fatalMitigatedBy: "health",
    textVariants: ["swelled up with the dropsy and slowly went down again."],
    deathText: ["died of the dropsy, swollen and serene."],
  },
  {
    id: "a_good_year_for_health",
    category: "disease",
    weight: 3,
    statEffects: { health: 1 },
    textVariants: ["a year of no illness at all. You hardly knew what to do."],
  },
  {
    id: "the_ergot",
    category: "disease",
    weight: 3,
    tags: ["plague"],
    fatal: 0.2,
    fatalMitigatedBy: "health",
    conditions: [{ flag: "badBread" }],
    textVariants: ["the bread ran strange and the whole village danced. You stopped in time."],
    deathText: ["died of St Anthony's fire, dancing, from bad rye."],
  },
];
