import type { EventDef } from "../../../../engine/types.js";

export const FAMILY: EventDef[] = [
  {
    id: "marriage",
    category: "family",
    weight: 6,
    conditions: [{ notFlag: "married", minAge: 16 }],
    setsFlags: ["married"],
    statEffects: { standing: 1 },
    textVariants: [
      "married Agnes. The dowry was a different pig.",
      "married well, by the standards of the parish, which are low.",
      "wed at the church door before witnesses and a suspicious priest.",
    ],
  },
  {
    id: "a_child",
    category: "family",
    weight: 7,
    tags: ["childGained"],
    conditions: [{ flag: "married" }],
    textVariants: [
      "a child arrived, squalling and welcome.",
      "another mouth, another pair of hands, eventually.",
      "a son was born and named after a saint you couldn't quite recall.",
    ],
  },
  {
    id: "child_lost",
    category: "family",
    weight: 4,
    tags: ["childLost"],
    conditions: [{ flag: "married" }],
    statEffects: { health: -1 },
    textVariants: [
      "buried a child that winter. Said little of it.",
      "a fever took one of the little ones. The parish register grew by a line.",
    ],
  },
  {
    id: "inheritance",
    category: "family",
    weight: 3,
    conditions: [{ flag: "married", minAge: 30 }],
    statEffects: { wealth: 2 },
    textVariants: ["an uncle died and, astonishingly, left you the cottage."],
  },
  {
    id: "inheritance_dispute",
    category: "family",
    weight: 3,
    conditions: [{ flag: "married", minAge: 35, statAtLeast: ["wealth", 3] }],
    statEffects: { standing: -1, suspicion: 1 },
    setsFlags: ["feud"],
    textVariants: ["a cousin contested the will. The feud would outlive you both."],
  },
  {
    id: "the_feud",
    category: "family",
    weight: 3,
    conditions: [{ flag: "feud" }],
    statEffects: { standing: -1 },
    textVariants: ["the feud with the cousins simmered on. Someone's hens kept vanishing."],
  },
  {
    id: "widowed",
    category: "family",
    weight: 3,
    conditions: [{ flag: "married", minAge: 30, notFlag: "widowed" }],
    setsFlags: ["widowed"],
    clearsFlags: ["married"],
    statEffects: { health: -1, standing: -1 },
    textVariants: ["Agnes died in the spring. The cottage was very quiet after."],
  },
  {
    id: "remarried",
    category: "family",
    weight: 3,
    conditions: [{ flag: "widowed", notFlag: "married" }],
    setsFlags: ["married"],
    clearsFlags: ["widowed"],
    statEffects: { standing: 1 },
    textVariants: ["remarried, sensibly, to a widow with a good field and better sense."],
  },
  {
    id: "a_wedding_feast",
    category: "family",
    weight: 3,
    tags: ["good"],
    conditions: [{ flag: "married" }],
    statEffects: { standing: 1, health: 1 },
    textVariants: ["a daughter married the miller's son. The feast lasted two days."],
  },
  {
    id: "grandchildren",
    category: "family",
    weight: 3,
    tags: ["good"],
    conditions: [{ minAge: 45, statAtLeast: ["standing", 3] }],
    statEffects: { standing: 1 },
    textVariants: ["grandchildren appeared, underfoot and delightful."],
  },
  {
    id: "a_good_dog",
    category: "family",
    weight: 3,
    tags: ["good"],
    conditions: [{ flag: "item:dog" }],
    statEffects: { health: 1 },
    textVariants: ["the dog saw off a wolf, a thief, and a tax collector, in that order of merit."],
  },
];
