import type { EventDef } from "../../../../engine/types.js";

export const FORTUNE: EventDef[] = [
  {
    id: "found_a_coin",
    category: "fortune",
    weight: 3,
    tags: ["good"],
    statEffects: { wealth: 1, standing: 1 },
    textVariants: ["found a silver penny in the mud and told no one."],
  },
  {
    id: "lords_favour",
    category: "fortune",
    weight: 2,
    tags: ["good"],
    statEffects: { standing: 2, wealth: 1 },
    textVariants: ["did the lord a small service and was, briefly, somebody."],
  },
  {
    id: "found_hoard",
    category: "fortune",
    weight: 1,
    tags: ["good"],
    statEffects: { wealth: 3, suspicion: 1 },
    textVariants: ["turned up a pot of old coins while ditching. Buried it again, then dug it up nightly to check."],
  },
  {
    id: "miracle_attributed",
    category: "fortune",
    weight: 1,
    tags: ["good"],
    conditions: [{ statAtLeast: ["standing", 4] }],
    statEffects: { standing: 2 },
    textVariants: ["a sick child recovered after you happened to pass. The story improved with each telling."],
  },
  {
    id: "good_market_day",
    category: "fortune",
    weight: 3,
    tags: ["good"],
    conditions: [{ flag: "village:market" }],
    statEffects: { wealth: 1 },
    textVariants: ["a good market day. Sold everything, bought little, walked home whistling."],
  },
  {
    id: "envy_of_neighbours",
    category: "fortune",
    weight: 3,
    conditions: [{ statAtLeast: ["wealth", 5] }],
    statEffects: { suspicion: 2 },
    textVariants: ["your small prosperity drew small eyes. Comfort attracts accusation."],
  },
  {
    id: "pilgrim_blessing",
    category: "fortune",
    weight: 2,
    tags: ["good"],
    statEffects: { health: 1, standing: 1 },
    textVariants: ["walked to a shrine and came back convinced it had worked, which is half the cure."],
  },
  {
    id: "a_fair_year",
    category: "fortune",
    weight: 4,
    tags: ["good"],
    statEffects: { health: 1 },
    textVariants: ["a year in which, against all local precedent, nothing bad happened."],
  },
  {
    id: "won_at_dice",
    category: "fortune",
    weight: 3,
    statEffects: { wealth: 1, suspicion: 1 },
    textVariants: ["won at dice at the tavern. The losers remembered; you forgot to be careful."],
  },
];
