import type { EventDef } from "../../../../engine/types.js";

export const JUSTICE: EventDef[] = [
  // --- witchcraft chain: accusation -> onTrial -> witch_trial ---
  {
    id: "accused_witchcraft",
    category: "justice",
    weight: 5,
    tags: ["accusation"],
    conditions: [{ notFlag: "onTrial" }],
    statEffects: { suspicion: 3, standing: -1 },
    setsFlags: ["onTrial"],
    textVariants: [
      "accused of witchcraft. Cleared, but the vibes lingered.",
      "named by a neighbour with a grudge and a poor memory.",
      "a cow died and a finger was pointed. The finger pointed at you.",
    ],
  },
  {
    id: "witch_trial",
    category: "justice",
    weight: 6,
    tags: ["accusation"],
    conditions: [{ flag: "onTrial", statAtLeast: ["suspicion", 4] }],
    fatal: 0.4,
    fatalMitigatedBy: "standing",
    clearsFlags: ["onTrial"],
    textVariants: ["stood trial, floated the wrong way, and somehow talked free."],
    deathText: [
      "was tried as a witch and did not float, which settled the matter.",
      "was found guilty of witchcraft on the word of a child and a chicken.",
    ],
  },
  {
    id: "cunning_reputation",
    category: "justice",
    weight: 3,
    tags: ["accusation"],
    conditions: [{ flag: "onTrial" }],
    statEffects: { suspicion: 1, wealth: 1 },
    textVariants: ["being half-suspected of witchcraft, you were quietly paid for charms. Enterprising."],
  },
  // --- ordinary justice ---
  {
    id: "the_stocks",
    category: "justice",
    weight: 5,
    statEffects: { standing: -1 },
    textVariants: [
      "a day in the stocks for 'insolence'. Mostly rotten fruit.",
      "an afternoon in the pillory. The children were merciless.",
    ],
  },
  {
    id: "manor_court_fine",
    category: "justice",
    weight: 6,
    statEffects: { wealth: -1 },
    textVariants: [
      "fined at the manor court for letting your pig root on the common.",
      "amerced tuppence for brewing weak ale. An insult, really.",
    ],
  },
  {
    id: "trial_by_ordeal",
    category: "justice",
    weight: 3,
    fatal: 0.25,
    fatalMitigatedBy: "health",
    conditions: [{ statAtLeast: ["suspicion", 3] }],
    textVariants: ["carried the hot iron nine paces and healed clean. Innocent, apparently."],
    deathText: ["failed the ordeal of cold water and was pronounced guilty, and drowned."],
  },
  {
    id: "poaching_caught",
    category: "justice",
    weight: 4,
    tags: ["downfall"],
    fatal: 0.3,
    fatalMitigatedBy: "standing",
    conditions: [{ statAtLeast: ["suspicion", 2] }],
    textVariants: ["caught with a hare and a story nobody believed. Fined."],
    deathText: ["was hanged for a deer that belonged to the Crown."],
  },
  {
    id: "false_witness",
    category: "justice",
    weight: 3,
    statEffects: { suspicion: 2, standing: -1 },
    textVariants: ["a neighbour swore falsely against you at the hundred court. You remember his name."],
  },
  {
    id: "frankpledge",
    category: "justice",
    weight: 3,
    statEffects: { wealth: -1 },
    textVariants: ["your tithing was fined for a crime none of you did. Collective responsibility, they call it."],
  },
  {
    id: "outlawed",
    category: "justice",
    weight: 3,
    tags: ["downfall"],
    conditions: [{ statAtLeast: ["suspicion", 5], notFlag: "outlaw" }],
    setsFlags: ["outlaw"],
    statEffects: { standing: -2 },
    textVariants: ["failed to appear at court once too often and were declared an outlaw. To the woods."],
  },
  {
    id: "outlaw_in_the_greenwood",
    category: "justice",
    weight: 4,
    tags: ["downfall"],
    conditions: [{ flag: "outlaw" }],
    fatal: 0.28,
    fatalMitigatedBy: "health",
    statEffects: { wealth: 1 },
    textVariants: ["lived off the greenwood a while. It was almost romantic, in the dry months."],
    deathText: ["was run down by the sheriff's men in the greenwood."],
  },
  {
    id: "coronation_pardon",
    category: "justice",
    weight: 2,
    tags: ["good"],
    conditions: [{ flag: "outlaw" }],
    clearsFlags: ["outlaw"],
    statEffects: { standing: 1, suspicion: -3 },
    textVariants: ["a new king was crowned and pardoned the outlaws. You came home, blinking."],
  },
  {
    id: "good_word_at_court",
    category: "justice",
    weight: 3,
    tags: ["good"],
    conditions: [{ statAtLeast: ["standing", 4] }],
    statEffects: { suspicion: -2 },
    textVariants: ["your good name spoke for you at the manor court. Standing has its uses."],
  },
];
