import type { EventDef } from "../../../../engine/types.js";

/** Church & superstition — a rich comedic vein of medieval life. */
export const RELIGION: EventDef[] = [
  {
    id: "pilgrimage",
    category: "religion",
    weight: 4,
    tags: ["good"],
    conditions: [{ minAge: 20 }],
    statEffects: { standing: 1, health: 1 },
    textVariants: [
      "walked to Walsingham and back and felt, on the whole, holier and footsore.",
      "made pilgrimage to a shrine and bought a small lead badge to prove it.",
    ],
  },
  {
    id: "pilgrimage_died",
    category: "religion",
    weight: 2,
    conditions: [{ minAge: 25 }],
    fatal: 0.3,
    fatalMitigatedBy: "health",
    textVariants: ["set out on a long pilgrimage and, miraculously, survived the road, the inns, and the company."],
    deathText: ["died on the road to Canterbury, which is at least a fashionable way to go."],
  },
  {
    id: "relic_purchase",
    category: "religion",
    weight: 4,
    statEffects: { wealth: -1, standing: 1 },
    textVariants: [
      "bought a splinter of the True Cross from a friar. It was the ninth such splinter in the county.",
      "acquired a saint's fingerbone of uncertain provenance and certain expense.",
    ],
  },
  {
    id: "confession",
    category: "religion",
    weight: 5,
    statEffects: { suspicion: -1 },
    textVariants: [
      "confessed your sins at Easter. The priest had heard worse, but not much worse, and not recently.",
      "did penance for a year of small sins and one memorable large one.",
    ],
  },
  {
    id: "church_ale",
    category: "religion",
    weight: 4,
    tags: ["good"],
    statEffects: { standing: 1, health: 1 },
    textVariants: ["the church-ale raised money for the steeple and the whole parish got magnificently drunk for God."],
  },
  {
    id: "saints_day_feast",
    category: "religion",
    weight: 4,
    tags: ["good"],
    statEffects: { health: 1 },
    textVariants: ["a saint's day meant no work and actual meat. You were briefly, piously content."],
  },
  {
    id: "tithe_barn_labour",
    category: "religion",
    weight: 4,
    statEffects: { health: -1 },
    textVariants: ["filled the great tithe barn with the Church's tenth. It was a very large barn."],
  },
  {
    id: "excommunication_threat",
    category: "religion",
    weight: 3,
    conditions: [{ statAtLeast: ["suspicion", 3] }],
    statEffects: { standing: -1 },
    textVariants: ["the priest threatened excommunication over unpaid tithes. You found the tithes."],
  },
  {
    id: "holy_well",
    category: "religion",
    weight: 4,
    tags: ["good"],
    statEffects: { health: 1 },
    textVariants: ["drank from the holy well of a local saint and credited it, rather than luck, with your recovery."],
  },
  {
    id: "comet_omen",
    category: "religion",
    weight: 3,
    statEffects: { suspicion: 1 },
    textVariants: [
      "a comet hung over the village for a week. Everyone agreed it foretold disaster; disaster, as ever, was already on the way.",
      "a blazing star crossed the sky and the priest preached for a month about it.",
    ],
  },
  {
    id: "wandering_friar",
    category: "religion",
    weight: 4,
    statEffects: { standing: 1 },
    textVariants: ["a wandering friar preached in the churchyard, ate your bread, blessed your pig, and moved on."],
  },
  {
    id: "penance_barefoot",
    category: "religion",
    weight: 3,
    conditions: [{ statAtLeast: ["suspicion", 2] }],
    statEffects: { suspicion: -2, health: -1 },
    textVariants: ["did public penance barefoot in the snow to quiet the gossip. It mostly worked, and cost two toes' worth of feeling."],
  },
  {
    id: "hermit_blessing",
    category: "religion",
    weight: 2,
    tags: ["good"],
    statEffects: { standing: 1, health: 1 },
    textVariants: ["the wood-hermit, who spoke to no one, spoke to you. The village never quite looked at you the same way again."],
  },
  {
    id: "dancing_mania",
    category: "religion",
    weight: 2,
    fatal: 0.18,
    fatalMitigatedBy: "health",
    conditions: [{ minAge: 16 }],
    textVariants: ["a dancing madness swept the parish. You danced three days, then stopped, unlike some."],
    deathText: ["danced without stopping in a fit of the dancing plague, until the heart gave out."],
  },
  {
    id: "flagellants",
    category: "religion",
    weight: 2,
    tags: ["plague"],
    conditions: [{ minAge: 18 }],
    statEffects: { health: -1, standing: 1 },
    textVariants: ["a band of flagellants passed through, whipping themselves for everyone's sins. You watched, uneasily impressed."],
  },
  {
    id: "miracle_play",
    category: "religion",
    weight: 3,
    tags: ["good"],
    statEffects: { standing: 1 },
    textVariants: ["played Second Shepherd in the guild's mystery play. Reviews were mixed but the ale was free."],
  },
  {
    id: "churchyard_gossip",
    category: "religion",
    weight: 4,
    statEffects: { suspicion: 1 },
    textVariants: ["Sunday after Mass was when the parish did its real business: gossip, grudges, and betrothals in the churchyard."],
  },
  {
    id: "indulgence_pardoner",
    category: "religion",
    weight: 3,
    statEffects: { wealth: -1, suspicion: -1 },
    textVariants: ["a pardoner sold you time off Purgatory at a competitive rate. You paid, just in case."],
  },
  {
    id: "chantry_prayers",
    category: "religion",
    weight: 2,
    tags: ["good"],
    conditions: [{ minAge: 40, statAtLeast: ["wealth", 4] }],
    statEffects: { standing: 1 },
    textVariants: ["paid for prayers to be said for your soul after death. An early and very medieval retirement plan."],
  },
  {
    id: "sanctuary",
    category: "religion",
    weight: 2,
    tags: ["good"],
    conditions: [{ statAtLeast: ["suspicion", 4] }],
    statEffects: { suspicion: -2 },
    textVariants: ["fled to the church and claimed sanctuary. Forty days of cold stone, but nobody could touch you."],
  },
];
