import type { EventDef } from "../../../../engine/types.js";

export const WAR: EventDef[] = [
  {
    id: "conscripted",
    category: "war",
    weight: 5,
    fatal: 0.28,
    fatalMitigatedBy: "health",
    conditions: [{ notFlag: "veteran" }],
    setsFlags: ["veteran"],
    textVariants: [
      "marched off to a war, and marched back with a limp and a tale.",
      "was levied for the king's army and, remarkably, returned.",
    ],
    deathText: ["fell at a battle whose name nobody local could pronounce."],
  },
  {
    id: "called_up_again",
    category: "war",
    weight: 4,
    fatal: 0.34,
    fatalMitigatedBy: "health",
    conditions: [{ flag: "veteran" }],
    textVariants: ["called up a second time. Knew what to expect, which helped less than you'd think."],
    deathText: ["fell in a second war, having survived the first out of spite."],
  },
  {
    id: "veterans_tales",
    category: "war",
    weight: 4,
    tags: ["good"],
    conditions: [{ flag: "veteran" }],
    statEffects: { standing: 1 },
    textVariants: ["your war stories bought free ale for years. Most were even true."],
  },
  {
    id: "old_war_wound",
    category: "war",
    weight: 4,
    conditions: [{ flag: "veteran", minAge: 40 }],
    statEffects: { health: -1 },
    textVariants: ["the old wound ached before rain, and it rained a great deal."],
  },
  {
    id: "coastal_raid",
    category: "war",
    weight: 4,
    tags: ["raid"],
    fatal: 0.25,
    fatalMitigatedBy: "health",
    textVariants: ["raiders came at dawn. Hid in the reeds until they left."],
    deathText: ["was cut down in a raid, defending a barn of turnips."],
  },
  {
    id: "billeting",
    category: "war",
    weight: 4,
    statEffects: { wealth: -1, health: -1 },
    textVariants: ["soldiers were quartered in your house. They ate everything and thanked no one."],
  },
  {
    id: "the_array",
    category: "war",
    weight: 3,
    statEffects: { wealth: -1 },
    textVariants: ["mustered for the array with a rusty bill and a borrowed helmet, then sent home."],
  },
  {
    id: "archery_by_law",
    category: "war",
    weight: 3,
    conditions: [{ notFlag: "gacha:longbow" }],
    statEffects: { health: 1 },
    textVariants: ["by law you practised at the butts every Sunday. It kept the arms strong."],
  },
  {
    id: "plunder",
    category: "war",
    weight: 2,
    tags: ["good"],
    conditions: [{ flag: "veteran" }],
    statEffects: { wealth: 2, suspicion: 1 },
    textVariants: ["came home from the war with a purse and a sword and no clear account of either."],
  },
];
