import type { BadgeDef } from "../../../engine/types.js";
import { hasEvent, survivedEvent } from "../../../engine/badges.js";

/**
 * Launch badge set. `baseRarity` is the DESIGNED global fraction, used by the
 * rarity service until real counts exist. Ordered loosely common -> legendary.
 */
export const BADGES: BadgeDef[] = [
  // --- near-universal ---
  {
    id: "a_life_lived",
    name: "A Life Lived",
    description: "Live, and then, inevitably, die.",
    icon: "hourglass",
    tier: "common",
    baseRarity: 0.99,
    predicate: () => true,
  },
  {
    id: "and_the_pig",
    name: "And the Pig",
    description: "Be survived by the pig.",
    icon: "pig",
    tier: "common",
    baseRarity: 0.62,
    predicate: (l) => l.flags.includes("married") || l.stats.childrenSurvived >= 1,
  },
  {
    id: "even_the_pig_left",
    name: "Even the Pig Left",
    description: "Be survived by no one at all.",
    icon: "alone",
    tier: "common",
    baseRarity: 0.45,
    predicate: (l) => !l.flags.includes("married") && l.stats.childrenSurvived === 0,
  },
  {
    id: "made_twenty",
    name: "Made It to Twenty",
    description: "Reach the ripe old age of 20.",
    icon: "candle",
    tier: "common",
    baseRarity: 0.55,
    predicate: (l) => l.ageAtDeath >= 20,
  },

  // --- uncommon ---
  {
    id: "plague_touched",
    name: "Plague-Touched",
    description: "Endure a plague and walk away.",
    icon: "plague",
    tier: "uncommon",
    baseRarity: 0.31,
    predicate: (l) => l.stats.plaguesEndured >= 1,
  },
  {
    id: "the_vibes_lingered",
    name: "The Vibes Lingered",
    description: "Be accused of witchcraft at least once.",
    icon: "eye",
    tier: "uncommon",
    baseRarity: 0.24,
    predicate: (l) => l.stats.timesAccused >= 1,
  },
  {
    id: "wed_in_the_parish",
    name: "Wed in the Parish",
    description: "Marry. The dowry was probably a pig.",
    icon: "ring",
    tier: "uncommon",
    baseRarity: 0.35,
    predicate: (l) => l.flags.includes("married"),
  },
  {
    id: "fruitful",
    name: "Fruitful",
    description: "Raise at least one surviving child.",
    icon: "cradle",
    tier: "uncommon",
    baseRarity: 0.22,
    predicate: (l) => l.stats.childrenSurvived >= 1,
  },
  {
    id: "veteran",
    name: "Marched and Returned",
    description: "Survive being sent off to war.",
    icon: "sword",
    tier: "uncommon",
    baseRarity: 0.18,
    predicate: (l) => survivedEvent(l, "conscripted") || survivedEvent(l, "coastal_raid"),
  },

  // --- rare ---
  {
    id: "old_bones",
    name: "Old Bones",
    description: "Reach the age of 50.",
    icon: "bones",
    tier: "rare",
    baseRarity: 0.15,
    predicate: (l) => l.ageAtDeath >= 50,
  },
  {
    id: "floated_the_wrong_way",
    name: "Floated the Wrong Way",
    description: "Stand a witch trial — and live.",
    icon: "witch",
    tier: "rare",
    baseRarity: 0.06,
    predicate: (l) => survivedEvent(l, "witch_trial"),
  },
  {
    id: "thrice_pestilent",
    name: "Thrice Pestilent",
    description: "Endure three plagues in one life.",
    icon: "plague",
    tier: "rare",
    baseRarity: 0.05,
    predicate: (l) => l.stats.plaguesEndured >= 3,
  },
  {
    id: "full_cottage",
    name: "A Full Cottage",
    description: "Be survived by four or more children.",
    icon: "cradle",
    tier: "rare",
    baseRarity: 0.04,
    predicate: (l) => l.stats.childrenSurvived >= 4,
  },

  // --- funny / specific deaths ---
  {
    id: "the_hay_cart_wins",
    name: "The Hay Cart Wins",
    description: "Die falling from a hay cart.",
    icon: "cart",
    tier: "rare",
    baseRarity: 0.03,
    predicate: (l) => l.deathCauseId === "hay_cart",
    hidden: true,
  },
  {
    id: "a_grudge_mutual",
    name: "A Grudge, Mutual",
    description: "Die by donkey.",
    icon: "hoof",
    tier: "rare",
    baseRarity: 0.02,
    predicate: (l) => l.deathCauseId === "kicked_by_donkey",
    hidden: true,
  },
  {
    id: "smitten",
    name: "Smitten",
    description: "Be struck by lightning mid-blasphemy.",
    icon: "bolt",
    tier: "epic",
    baseRarity: 0.012,
    predicate: (l) => l.deathCauseId === "lightning_blasphemy",
    hidden: true,
  },
  {
    id: "hanged_for_a_deer",
    name: "Hanged for a Deer",
    description: "Be executed for poaching the Crown's game.",
    icon: "noose",
    tier: "epic",
    baseRarity: 0.02,
    predicate: (l) => l.deathCauseId === "poaching_caught",
    hidden: true,
  },
  {
    id: "did_not_float",
    name: "Did Not Float",
    description: "Be tried as a witch, and lose.",
    icon: "witch",
    tier: "epic",
    baseRarity: 0.018,
    predicate: (l) => l.deathCauseId === "witch_trial",
    hidden: true,
  },

  // --- epic / legendary ---
  {
    id: "death_refunded",
    name: "Death, Refunded",
    description: "Be spared by a papal indulgence.",
    icon: "indulgence",
    tier: "epic",
    baseRarity: 0.01,
    predicate: (l) => l.savedBy === "indulgence",
    hidden: true,
  },
  {
    id: "a_good_death",
    name: "A Good Death",
    description: "Die peacefully in bed, aged 70 or more.",
    icon: "laurel",
    tier: "epic",
    baseRarity: 0.02,
    predicate: (l) => l.goodDeath,
  },
  {
    id: "methuselah",
    name: "Methuselah of the Manor",
    description: "Reach the impossible age of 80.",
    icon: "laurel",
    tier: "legendary",
    baseRarity: 0.003,
    predicate: (l) => l.ageAtDeath >= 80,
    hidden: true,
  },
  {
    id: "blessed_existence",
    name: "A Blessed Existence",
    description: "Reach a good death, never once accused, with a full cottage of children.",
    icon: "star",
    tier: "legendary",
    baseRarity: 0.001,
    predicate: (l) =>
      l.goodDeath && l.stats.timesAccused === 0 && l.stats.childrenSurvived >= 3,
    hidden: true,
  },
];
